name: 🤖 AI Code Review

on:
  pull_request:
    # We only want to run on these events to avoid spamming
    types: [opened, synchronize] 

jobs:
  review:
    runs-on: ubuntu-latest

    # These permissions are needed for the checkout action and to post comments
    permissions:
      contents: read
      pull-requests: write 

    steps:
      - name: 1. Check out repository
        uses: actions/checkout@v4
        with:
          # We need the full history to be able to diff against the base branch
          fetch-depth: 0 

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: 4. Run AI Review Script
        env:
          # Pass all our secrets and context to the Python script
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }} 
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          python .github/scripts/review.py
